### ISSUE TITLE
Problem with contextmenu 

### ISSUE THREAD

**Issue by giosifelis** [theyak/contextmenu#5]
first of all congrats  on this.  its very good. 

I found a small bug.  on ContextMenu.attach if i use  event: "contextmenu", the menu items inferit a "contextmenu" event  instead of a "click" event.

i propose changing line 290 from 

`item.addEventListener(target.ctxMenu.event, function(e) {`

 to:

`item.addEventListener('click', function(e) {`

I tried it and it works.  
What do you think?

**Comment by theyak** [comment]
This seems correct. When I made this years ago I used the click event for the handler, so that propagated to the items, and therefore made this stupid error. Could probably be even made more robust by sending an event parameter to the item, defaulting to click. I'll make the click change. If anyone wants to add the event property to the item and make a PR, I'll take a look.

**Comment by theyak** [comment]
Fixed in https://github.com/theyak/contextmenu/commit/07850f4e752c60ca9d5af7dffbf2d9f6283e352a
